///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesAppLogo = 'assets/images/app_logo.png';
  static const String imagesBox = 'assets/images/box.png';
  static const String imagesCoin = 'assets/images/coin.png';
  static const String imagesDarkBg = 'assets/images/darkBg.jpeg';
  static const String imagesDelivery = 'assets/images/delivery.png';
  static const String imagesEmptyCart = 'assets/images/emptyCart.png';
  static const String imagesFast = 'assets/images/fast.png';
  static const String imagesInviteLeftBottom = 'assets/images/invite_left_bottom.png';
  static const String imagesInviteLeftTop = 'assets/images/invite_left_top.png';
  static const String imagesInviteRightBottom = 'assets/images/invite_right_bottom.png';
  static const String imagesInviteRightTop = 'assets/images/invite_right_top.png';
  static const String imagesLightBg = 'assets/images/lightBg.jpeg';
  static const String imagesLoginBg = 'assets/images/loginBg.png';
  static const String imagesOrderSuccess = 'assets/images/order_success.png';
  static const String imagesPaymentRejected = 'assets/images/payment_rejected.png';
  static const String imagesSave = 'assets/images/save.png';
  static const String imagesSet = 'assets/images/set.png';
  static const String imagesUiFour = 'assets/images/ui_four.png';
  static const String imagesUiOne = 'assets/images/ui_one.png';
  static const String imagesUiThree = 'assets/images/ui_three.png';
  static const String imagesUiTwo = 'assets/images/ui_two.png';
  static const String lottieEmptyList = 'assets/lottie/empty_list.json';
  static const String lottieEmptyReview = 'assets/lottie/empty_review.json';
  static const String lottieNoImage = 'assets/lottie/noImage.json';
  static const String lottieNoItem = 'assets/lottie/noItem.json';
  static const String lottieNotificationEmpty = 'assets/lottie/notification_empty.json';
  static const String lottieOrderNot = 'assets/lottie/order_not.json';
  static const String lottiePin = 'assets/lottie/pin.json';
  static const String lottieProcessing = 'assets/lottie/processing.json';
  static const String svgAccepted = 'assets/svg/accepted.svg';
  static const String svgBag = 'assets/svg/bag.svg';
  static const String svgCategory = 'assets/svg/category.svg';
  static const String svgContact = 'assets/svg/contact.svg';
  static const String svgDiscount = 'assets/svg/discount.svg';
  static const String svgFilter = 'assets/svg/filter.svg';
  static const String svgHome = 'assets/svg/home.svg';
  static const String svgIcCertificateCheck = 'assets/svg/ic_certificate_check.svg';
  static const String svgIcDelivery = 'assets/svg/ic_delivery.svg';
  static const String svgIcLocationStar = 'assets/svg/ic_location_star.svg';
  static const String svgInStock = 'assets/svg/inStock.svg';
  static const String svgLike = 'assets/svg/like.svg';
  static const String svgMenu = 'assets/svg/menu.svg';
  static const String svgOutOfStock = 'assets/svg/outOfStock.svg';
  static const String svgSelectBag = 'assets/svg/selectBag.svg';
  static const String svgSelectHome = 'assets/svg/selectHome.svg';
  static const String svgSelectLike = 'assets/svg/selectLike.svg';
  static const String svgSelectMenu = 'assets/svg/selectMenu.svg';
  static const String svgStart = 'assets/svg/start.svg';

}
